[package]
authors = ["Fabien Bellanger <befrain411@gmail.com>"]
description = "ESC/POS printer driver"
documentation = "https://docs.rs/escpos"
edition = "2021"
homepage = "https://github.com/efrain2007/escpos.git"
keywords = ["escpos", "printer", "driver", "pos", "usb"]
license = "MIT"
name = "escpos"
readme = "README.md"
repository = "https://github.com/efrain2007/escpos.git"
version = "1.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
codes_2d = []
barcodes = []
default = ["barcodes", "codes_2d"]
full = ["barcodes", "codes_2d", "graphics"]
graphics = ["dep:image"]

[dependencies]
encoding_rs = "0.8.33"
image = { version = "0.24.7", optional = true }
log = "0.4.20"

[dev-dependencies]
env_logger = "0.10.1"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
